data:
  image_path: "data/images/dog.jpg"
  target_image_path: "data/images/dance-twirl.jpg"


video:
  height: 480
  width: 832
  num_frames: 17  
  denoising_steps: 25   


prompt:
  source: "A golden retriever walks gracefully through a grassy field, sniffing the ground and exploring its surroundings. As it moves, its tail wags gently, reflecting its curiosity and excitement with each step."
  target: "A jet fighter accelerates rapidly into the sky, performing a series of dramatic barrel rolls and high-speed maneuvers. The plane emits loud sonic booms as it streaks across the clouds, creating a visually explosive display."


attack:
  num_steps: 500
  epsilon: "40/255*2"