attack:
  epsilon: 40/255*2
  num_steps: 500
data:
  image_path: data/images/hike.jpg
  target_image_path: data/images/picking.jpg
prompt:
  source: A hiker walks steadily along a rocky mountain trail, surveying the breathtaking landscape around him with a sense of adventure. Each step is deliberate, as he navigates the uneven terrain, shifting his weight smoothly from one foot to the other while adjusting his backpack.
  target: A vibrant purple dragon bursts into the scene, soaring dramatically through the sky with powerful flaps of its massive wings. It twirls and dives with intense speed, leaving a trail of fiery sparks as it performs an explosive aerial acrobatics.
video:
  denoising_steps: 25
  height: 480
  num_frames: 17
  width: 832
