attack:
  epsilon: 40/255*2
  num_steps: 500
data:
  image_path: data/images/car-turn.jpg
  target_image_path: data/images/swing.jpg
prompt:
  source: The silver SUV navigates smoothly around the winding mountain road, its tires gripping the asphalt as it accelerates steadily. With each curve, the vehicle leans gently, showcasing its agility while the driver enjoys the stunning scenery around them.
  target: A massive dragon bursts from the mountain, flapping its enormous wings and soaring high into the sky. It breathes fire as it spirals downwards, creating a breathtaking but chaotic display of power and intensity.
video:
  denoising_steps: 25
  height: 480
  num_frames: 17
  width: 832